config/routes.rb
Rails.application.routes.draw do
  resources :admin
  root 'shops#index'
  resources :items
  get "/shops/:user_id", to: 'shops#items'
  get "/shops/:user_id/:id", to: 'shops#show'
  get 'cart_items/add', as: 'add_cart_item'
  get 'cart_items/buy', as: 'buy_cart_item'
  get 'cart_items/empty', as: 'empty_cart_item'
  resources :cart_items
  get 'orders/checkout', as: 'checkout_order'
  get 'orders/empty', as: 'empty_order'
  resources :orders
  #root 'home#index'
  devise_for :users, :controllers => {registrations: 'registrations'}
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/controllers/shops_controller.rb
class ShopsController < ApplicationController
  def index
    if user_signed_in?
      if current_user.admin
        redirect_to admin_index_path
      end
      if current_user.user_type == 'Vendor'
        redirect_to items_path
      end
    end
    @shops = User.where("user_type = 'Vendor'").search(params[:search]).all
  end

  def items
    @items = Item.where("user_id = #{params[:user_id]}").all
  end

  def show
    @item = Item.find(params[:id])
  end
end

app/helpers/shops_helper.rb
module ShopsHelper
end

app/views/shops/index.html.erb
<h1>Shops</h1>
<br>

<div class="container">
  <div class="row">
    <% @shops.each do |shop| %>
    <a href="/shops/<%= shop.id %>">
        <div class="card" style="width: 18.8rem; margin: 10px;">
            <%= image_tag(shop.thumbnail()) %>
            <div class="card-body">
              <h5 class="card-title"><%= shop.shop %></h5>
            </div>
        </div>
    </a>
    <% end %>
  </div>
</div>
<br/><br/>

app/views/shops/items.html.erb
<h1>Items</h1>
<br>

<div class="container">
  <div class="row">
    <% @items.each do |item| %>
      <% if item.quantity > 0 %>
        <a href="/shops/<%= item.user_id %>/<%= item.id %>">
        <div class="card" style="width: 18.8rem; margin: 10px;">
          <%= image_tag(item.thumbnail(0)) %>
          <div class="card-body">
            <h5 class="card-title"><%= item.name %></h5>
        </a>
            <p>
              <%= item.description %><br>
            </p>
            <strong>Price: &#8377;</strong><%= item.price %>
          </div>
        </div>
      <% end %>
    <% end %>
  </tbody>
</table>

app/views/shops/show.html.erb
<div class="jumbotron">
  <% (0...@item.images.count).each do |image| %>
    <%= image_tag(@item.thumbnail(image), style:"margin: 10px;") %>
  <% end %>
  <br><br>
  <h1 class="display-4">
    <%= @item.name %>
  </h1>
  <p class="lead">
    <%= @item.description %><br>
    <strong>Price: &#8377;</strong>
    <%= @item.price %>
  </p>
  <br>
  <%= link_to add_cart_item_path(:id=>@item), class:"btn btn-warning text-white" do %>
    <i class="fas fa-shopping-cart"></i> Add to Cart
  <% end %>
  <%= link_to buy_cart_item_path(:id=>@item), class:"btn btn-success" do %>
    <i class="fas fa-bolt"></i> Buy Now
  <% end %>
</div>