config/routes.rb
Rails.application.routes.draw do
  resources :admin
  root 'shops#index'
  resources :items
  get "/shops/:user_id", to: 'shops#items'
  get "/shops/:user_id/:id", to: 'shops#show'
  get 'cart_items/add', as: 'add_cart_item'
  get 'cart_items/buy', as: 'buy_cart_item'
  get 'cart_items/empty', as: 'empty_cart_item'
  resources :cart_items
  get 'orders/checkout', as: 'checkout_order'
  get 'orders/empty', as: 'empty_order'
  resources :orders
  #root 'home#index'
  devise_for :users, :controllers => {registrations: 'registrations'}
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/home/_header.html.erb
<nav class="navbar navbar-expand-lg navbar-dark bg-primary">
    <div class="container">
        <%= link_to 'GroceryStore', root_url, data: { turbolinks: false }, class:"navbar-brand" %>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>

        <div class="collapse navbar-collapse" id="navbarSupportedContent">
            <% if user_signed_in? %>
                <% if current_user.admin == false && current_user.user_type == "Customer" %>
                    <%= form_tag root_path, :method=>"get", :class=>"form-inline my-2 my-lg-0" do %>
                        <%= text_field_tag :search,params[:search], class:"form-control mr-sm-2", placeholder:"Search for shop" %>
                        <%= submit_tag("Search",:name => nil, :class => "btn btn-outline-light my-2 my-sm-0") %>
                    <%end%>
                <% end %>
            <% else %>
                <%= form_tag root_path, :method=>"get", :class=>"form-inline my-2 my-lg-0" do %>
                    <%= text_field_tag :search,params[:search], class:"form-control mr-sm-2", placeholder:"Search for shop" %>
                    <%= submit_tag("Search",:name => nil, :class => "btn btn-outline-light my-2 my-sm-0") %>
                <%end%>
            <% end %>
            <ul class="navbar-nav ml-auto">
                <% if user_signed_in? %>
                    <% usertype = current_user.user_type %>
                    <% if usertype == "Vendor" %>
                        <li class="nav-item active">
                            <%= link_to 'Items', items_path ,class:"nav-link"%>
                        </li>
                        <li class="nav-item active">
                            <%= link_to 'Add Item', new_item_path ,class:"nav-link"%>
                        </li>
                    <% end %>
                    <% if usertype == "Customer" && current_user.admin !=true %>
                        <li class="nav-item active">
                            <%= link_to orders_path, class:"nav-link" do %>
                                <i class="fas fa-shopping-bag"></i> Orders
                            <% end %>
                        </li>
                        <li class="nav-item active">
                            <%= link_to cart_items_path, data: { turbolinks: false }, class:"nav-link" do %>
                                <i class="fas fa-shopping-cart"></i> Cart
                            <% end %>
                        </li>
                    <% end %>
                    <li class="nav-item active">
                        <%= link_to edit_user_registration_path, class:"nav-link" do %>
                            <i class="fas fa-user-circle"></i> Edit Profile
                        <% end %>
                    </li>
                    <li class="nav-item active">
                        <%= link_to destroy_user_session_path, method: :delete, class:"nav-link" do %>
                            <i class="fas fa-sign-out-alt"></i> Logout
                        <% end %>
                    </li>
                <% else %>
                    <li class="nav-item active">
                        <%= link_to new_user_registration_path, class:"nav-link" do %>
                            <i class="fas fa-user-plus"></i> Sign Up
                        <% end %>
                    </li>
                    <li class="nav-item active">
                        <%= link_to new_user_session_path, class:"nav-link" do %>
                            <i class="fas fa-sign-in-alt"></i> Sign In
                        <% end %>
                    </li>
                <% end %>
            </ul>
        </div>
    </div>
</nav>

app/views/home/index.html.erb
<h1>Home#index</h1>
<% if user_signed_in? %>
    <%= link_to 'Sign Out', destroy_user_session_path, method: :delete, class:"nav-link" %>
    <%= link_to 'Edit Profile', edit_user_registration_path, class:"nav-link" %>
    <% usertype = current_user.user_type %>
    <% if usertype == "Vendor" %>
        <%= link_to 'Items', items_path %>
        <%= link_to 'Add Item', new_item_path %>
    <% end %>
<% else %>
    <%= link_to 'Sign Up', new_user_registration_path, class:"nav-link" %>
    <%= link_to 'Sign In', new_user_session_path, class:"nav-link" %>
<% end %>