config/routes.rb
Rails.application.routes.draw do
  resources :admin
  root 'shops#index'
  resources :items
  get "/shops/:user_id", to: 'shops#items'
  get "/shops/:user_id/:id", to: 'shops#show'
  get 'cart_items/add', as: 'add_cart_item'
  get 'cart_items/buy', as: 'buy_cart_item'
  get 'cart_items/empty', as: 'empty_cart_item'
  resources :cart_items
  get 'orders/checkout', as: 'checkout_order'
  get 'orders/empty', as: 'empty_order'
  resources :orders
  #root 'home#index'
  devise_for :users, :controllers => {registrations: 'registrations'}
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/cart_item.rb
class CartItem < ApplicationRecord
    belongs_to :user
    belongs_to :item
end

app/controllers/cart_items_controller.rb
class CartItemsController < ApplicationController
  before_action :authenticate_user!, except: []
  before_action :correct_user, except: []

  def index
    @items = CartItem.where(:user_id => current_user.id).all
    if @items.count == 0
      redirect_to empty_cart_item_path
    end
  end

  def empty
  end

  def add
    @item = Item.find(params[:id])
    itemid = @item.id
    itemuserid = @item.user_id
    userid = current_user.id
    price = @item.price
    @cart_item = CartItem.where("user_id = #{userid} and item_id = #{itemid}")
    if @cart_item.count == 0
      available = @item.quantity
      name = @item.name
      description = @item.description
      quantity = 1
      CartItem.create(:name=>name, :description=>description, :price=>price, :quantity=>quantity, :user_id=>userid, :item_id=>itemid, :available=>available)
    else
      @cart_item = @cart_item.first
      @cart_item.quantity += 1
      @cart_item.price += price
      @cart_item.save
    end
    redirect_to "/shops/#{itemuserid}/#{itemid}"
  end

  def buy
    @item = Item.find(params[:id])
    itemid = @item.id
    userid = current_user.id
    price = @item.price
    @cart_item = CartItem.where("user_id = #{userid} and item_id = #{itemid}")
    if @cart_item.count == 0
      available = @item.quantity
      name = @item.name
      description = @item.description
      quantity = 1
      CartItem.create(:name=>name, :description=>description, :price=>price, :quantity=>quantity, :user_id=>userid, :item_id=>itemid, :available=>available)
    else
      @cart_item = @cart_item.first
      @cart_item.quantity += 1
      @cart_item.price += price
      @cart_item.save
    end
    redirect_to cart_items_path
  end

  def update
    @item = CartItem.find(params[:id])
    updateditems = item_params
    if updateditems["quantity"].to_i < 1
      redirect_to cart_items_path, notice: "Quantity should be greater than or eqaul to 1."
    else
      price = @item.price / @item.quantity
      updateditems["price"] = price * updateditems["quantity"].to_i
      if @item.update(updateditems)
        redirect_to cart_items_path
      else
        redirect_to cart_items_path
      end
    end
  end

  def destroy
    @item = CartItem.find(params[:id])
    @item.destroy

    redirect_to cart_items_path
  end

  def correct_user
    usertype = current_user.user_type
    unless
      usertype == "Customer" &&
      current_user.admin == false
      redirect_to root_url, notice: "Not Authorized To Access Cart"
    end
  end

  private
    def item_params
      params.require(:cart_item).permit(:name, :description, :price, :quantity, :user_id, :item_id)
    end

end

app/helpers/cart_items_helper.rb
module CartItemsHelper
end

app/views/cart_items/empty.html.erb
<br><br>
<center>
    <i class="fas fa-cart-arrow-down fa-10x" style="color: #ffff66;"></i>
    <br><br>
    <h1>Your cart is empty!</h1>
    <br>
    <h4>Add items to it now</h4>
    <br>
    <%= link_to "Shop Now", root_path, class:"btn btn-primary" %>
</center>

app/views/cart_items/index.html.erb
<h1>Cart</h1>
<br>

<table class="table">
  <thead class="thead-light">
    <tr>
      <th scope="col">Name</th>
      <th scope="col">Description</th>
      <th scope="col">Quantity</th>
      <th scope="col">Price</th>
      <th scope="col" colspan="2"></th>
    </tr>
  </thead>

  <tbody>
    <% total = 0 %>
    <% @items.each do |item| %>
      <%= simple_form_for(item) do |form| %>
        <%= form.text_field :name, type: :hidden %>
        <%= form.text_area :description, style: "#{'display:none'}" %>
        <%= form.number_field :price, type: :hidden %>
        <%= form.number_field :quantity, type: :hidden %>
        <tr>
          <th scope="row"><a href="/shops/<%= item.user_id %>/<%= item.item_id %>"><%= item.name %></a></th>
          <td><%= item.description %></td>
          <td><%= form.number_field :quantity, min: 1, max: item.available, class:"form-control" %></td>
          <td><%= item.price %></td>
          <td><%= form.button :submit, class:"btn btn-outline-success btn-sm" %></td>
          <td><%= link_to 'Destroy', cart_item_path(item), method: :delete, data: { confirm: 'Are you sure?' }, class:"btn btn-outline-danger btn-sm" %></td>
          <% if item.quantity > item.available %>
            <td><p style="color: red">Available = <%= item.available %></p></td>
          <% end %>
        </tr>
        <% total += item.price %>
      <% end %>
    <% end %>
    <tr>
        <th colspan="3">Total</th>
        <td colspan="2"><%= total %></td>
        <td></td>
    </tr>
  </tbody>
</table>

<br/>
<%= link_to 'Place Order', checkout_order_path, class:"btn btn-success" %>